add change to combustion script to allow virtual cdrom iso

diff --git a/combustion b/combustion
--- a/combustion
+++ b/combustion
@@ -51,6 +51,17 @@ if [ "${1-}" = "--prepare" ]; then
 		rmdir "${config_mount}"
 	done
 
+	if ! [ -d "/sysroot/combustion" ]; then
+		if ! cp -R "/sysroot/combustion" "${config_dir}"; then
+  				echo "Failed to copy config!"
+  				rm -rf "${config_dir}"
+  				exit 1
+  			fi
+  	else
+  			echo "No config found on /sysroot."
+  	fi
+  fi
+
 	if ! [ -d "${config_dir}" ]; then
 		echo "No config source found"
 		exit 0
